# docker-compose.yml 파일 생성
version: '3.8'

services:
    postgres:
        image: postgres:17
        environment:
            POSTGRES_DB: puzzlecraft_db
            POSTGRES_USER: puzzlecraft
            POSTGRES_PASSWORD: puzzlecraft123
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    api-gateway:
        build: ./backend/api-gateway
        ports:
            - "8000:8000"
        environment:
            - DATABASE_URL=postgresql://puzzlecraft:puzzlecraft123@postgres:5432/puzzlecraft_db
            - REDIS_URL=redis://redis:6379
        depends_on:
            - postgres
            - redis
            - auth-service
            - game-manager
        volumes:
            - ./backend/api-gateway:/app

    auth-service:
        build: ./backend/auth-service
        ports:
            - "8001:8001"
        environment:
            - DATABASE_URL=postgresql://puzzlecraft:puzzlecraft123@postgres:5432/puzzlecraft_db
            - SECRET_KEY=your-secret-key-here-change-in-production-make-it-very-long-and-random
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=30
        depends_on:
            - postgres
        volumes:
            - ./backend/auth-service:/app

    game-manager:
        build: ./backend/game-manager
        ports:
            - "8002:8002"
        environment:
            - DATABASE_URL=postgresql://puzzlecraft:puzzlecraft123@postgres:5432/puzzlecraft_db
            - SECRET_KEY=your-secret-key-here-change-in-production-make-it-very-long-and-random
            - ALGORITHM=HS256
        depends_on:
            - postgres
            - auth-service
        volumes:
            - ./backend/game-manager:/app

volumes:
    postgres_data:
