# docker-compose.yml 파일 생성
version: '3.8'

services:
    postgres:
        image: postgres:17
        environment:
            POSTGRES_DB: puzzlecraft
            POSTGRES_USER: puzzlecraft
            POSTGRES_PASSWORD: puzzlecraft
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    api-gateway:
        build: ./backend/api-gateway
        ports:
            - "8000:8000"
        environment:
            - DATABASE_URL=postgresql://puzzlecraft:puzzlecraft@postgres:5432/puzzlecraft
            - REDIS_URL=redis://redis:6379
        depends_on:
            - postgres
            - redis
        volumes:
            - ./backend/api-gateway:/app

volumes:
    postgres_data: